### ISSUE TITLE
when to use /usr/bin/env python, python -m pip

### ISSUE THREAD

**Issue by gsemet** [wilfredinni/python-cheatsheet#26]
They are less seen in the wild but really useful to maximize code compatibility

**Comment by Raghavarora27** [comment]
when to use /usr/bin/env python ->> Answer is 
Using /usr/bin/env/ in python serves one more purpose. As python supports virtual environments, using /usr/bin/env python will make sure that your scripts runs inside the virtual environment, if you are inside one. Whereas, /usr/bin/python will run outside the virtual environment. In addition to the answers given above, the use of /usr/bin/env allows your Python to be installed in non-standard places, and as long as your PATH is set-up correctly, the script will run unmodified on any UNIX-style system that has /usr/bin/env. This includes any modern version of Linux and OS/X.

when to use python -m pip ->> Answer is 
What is pip?
pip is the standard package manager for Python. We can use pip to install additional packages that are not available in the Python standard library. For example,
pip install numpy  (this library is installed using pip because numpy makes simple while dealing with array)
If we had installed pip on our system, this command would have installed the numpy library.
